<?php
/**
 * @file
 * media_room.strongarm.inc
 */

/**
 * Implements hook_strongarm().
 */
function media_room_strongarm() {
  $export = array();

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'uuid_features_entity_file_video';
  $strongarm->value = 'video';
  $export['uuid_features_entity_file_video'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'uuid_features_file_file_video';
  $strongarm->value = 'video';
  $export['uuid_features_file_file_video'] = $strongarm;

  return $export;
}
