<?php
/**
 * @file
 * icons_taxonomy.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function icons_taxonomy_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'tree',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '05337d31-ddd7-4687-bccd-aac9b6b13463',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'fax',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '07b0f213-6556-4bb1-8c6d-aebf9a5aa0c5',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'thumbs-up',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '0a185a84-002f-4897-8187-da7d6a5aa624',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'industry',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '14ad1a59-75da-4973-a262-7b011278f96e',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'calendar',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '1e56f0c4-a2a5-4f22-a0d9-cd94d95efe0e',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'building-o',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '1f6fff19-8fb7-4c3c-a162-280df2737df4',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'lock',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '1fe603e3-c3b8-46e2-a891-a7816fcb85d3',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'balance-scale',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '2246d37d-444a-4d5e-b105-8e48e7063478',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'ambulance',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '27413bea-c897-44ce-adae-edb4b7142351',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'desktop',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '2e820cca-c47e-4cb4-b281-44a3fd18601b',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'phone',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '33c96b9f-26eb-4d66-aaf2-dd6b1366cc2c',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'child',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '3773f1cb-914f-4cd5-85db-09a25803c8df',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'heartbeat',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '3899e38c-1371-48ae-be01-64f058bf9771',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'bullseye',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '3b619872-95ad-44f9-962c-dbe0af641761',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'binoculars',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '3c538d89-2d0c-4efc-8eef-21640fa9ef16',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'hospital-o',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '3ecdb9a2-ab12-44c4-b5e6-5c7c860870ac',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'comments',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '41fffc87-0981-4387-a128-a45d4b304bb4',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'lightbulb-o',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '43749dcf-ebf2-49c4-874c-471c62d8b3cd',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'envelope',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '45d1023b-ef10-4038-a660-5cf62b8acb06',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'institution',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '4642b267-6e0d-4661-978e-5b92fc23bfe3',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'comment',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '4754214a-4cca-4495-8ffe-8d6f272a77e0',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'check-circle',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '495d0a7a-77d5-43d5-a507-6435fece1ee5',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'bus',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '55f45e41-71d1-41cb-bc24-3b8eb5e360a9',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'map',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '56dbc876-1e5e-46e5-8422-fbe1385ab7bc',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'taxi',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '59bd1cdf-c8b4-4b28-a4ca-c488ae49867d',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'camera',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '5cfdf172-3cc9-43f3-92fb-0bc81672cbd6',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'briefcase',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '634d713a-6d2e-4e1d-90e3-4b29c419cfda',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'user',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '65b54a31-ac9c-4b8c-b105-f8b29ad8ddd8',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'life-saver',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '6acbc54b-bcbf-4e55-a396-359cbff572b6',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'recycle',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '71bb4eaf-0ff6-44e6-9aa4-f5b8e127c071',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'flag',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '72b15ac3-7c42-431e-b9ae-fd33a369f253',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'clock-o',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '8236fdb2-c8d0-436d-9b7b-d4bf379b8384',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'users',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '82b3a57e-00a4-417e-8a04-e504bd2db1de',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'archive',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '83f8e2a2-0822-460d-920b-847a743e5310',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'legal',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '873d1c64-234c-4231-83eb-67a7fb963c94',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'university',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '8f4fb8e7-5498-454f-b270-eac9d69c54b4',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'calculator',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '9346223b-edf6-4bbd-8f33-af31e0ea1d8d',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'globe',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '9adb7569-f526-43d1-b108-3482a084bf44',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'bar-chart',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '9f8d269e-3112-4e51-b93a-18cb537af1c1',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'key',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'a38e5e3e-3dcb-44ed-b113-110715fcab3b',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'bed',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'a9bf807a-ed79-42ac-ad73-50482c7a1e35',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'info',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'b0b53725-8403-42aa-8b0e-f54bd286aa2f',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'car',
    'description' => 'A car',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'b2ac9820-5f42-493a-82ab-d74d3a707fd4',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'book',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'b41d37ff-7a8a-44eb-9881-54ea3fbf79d0',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'eye',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'b436e514-88c6-4bf9-9434-adea3fb8d245',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'certificate',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'b49d4c2b-1dca-4d8c-919a-f53ab559fa72',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'check',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'b5e7132d-e29c-43e6-b333-dc1b70e6aeb4',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'bicycle',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'ba759b57-6daf-4c69-a80a-b7b1fb35bf3a',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'building',
    'description' => 'A black building',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'bf129741-0fd8-4634-8132-1692f4785297',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'star',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'c16c98ea-338a-4302-bb8b-eaf9a141f9ba',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'group',
    'description' => 'A group of people',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'c802ed28-f2a6-48b7-9f6a-4c3d74b1e01f',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'medkit',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'c881fb84-7456-4de3-b181-fa8de18d7d2c',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'cogs',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'cef26c96-26cb-474e-bfaa-d31b8c11eaef',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'bullhorn',
    'description' => 'A bullhorn',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'cfb6a8a2-d6bb-4583-bf7e-59766d7ed4b2',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'compass',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'd215a2d0-0ae9-440b-84ac-016077006d2f',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'female',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'd54d8c6f-83a4-4762-a3aa-1ba69cd328ae',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'home',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'db2c0a6d-116b-4038-bc11-e607770e1a5c',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'newspaper-o',
    'description' => 'A newspaper outline',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'dda87f35-0de2-479c-a093-4b4ceefcb304',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'leaf',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'de0610ae-657f-4fd0-a47e-de6831ff2660',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'road',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'e00e4c97-fa94-44f1-8200-7d4deeb4c277',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'wrench',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'e01de7dd-bfe0-49aa-9e83-d8f01fbee7f6',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'paw',
    'description' => 'An animal paw',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'e26aa059-9d80-40df-addf-db4a5b2cfcf1',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'folder',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'e6851fb0-f70a-469a-878c-de6469e2ef8e',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'bullhorn',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'e6917722-aec5-4c29-9f01-0ce611f1af41',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'line-chart',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'eaa311cc-1b00-4020-bca4-14b857d01931',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'trash',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'eb111bf7-e9ef-457e-83ce-35cb139fae23',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'fire-extinguisher',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'eb886256-6a38-44e4-87e5-ca702ddc016c',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'graduation-cap',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'eba94988-309d-46a7-b636-d09414a56c10',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'male',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'ebe10e0f-cba8-4188-b211-a88fabca6bed',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'bank',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'efdb6ea2-b58b-4fc1-993b-fa8b3234c2c5',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'bookmark',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'f446ed0a-17f2-4dd8-8235-5763ab495ae2',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'truck',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'f4fefade-36ed-4c18-99a3-ea9f3a911eda',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'gavel',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'f8e128c9-d90b-4d87-b866-87a0752f58f5',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'cog',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'f9943be9-568b-4224-b8f4-1d3e8370abf6',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'bell',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'fc57fc51-dbcc-4a8e-ad52-854977308b7c',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'pie-chart',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'fe2d1bd7-b49d-45b2-87c0-9658de84fe9e',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'ban',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'fe9d6c0b-a30d-4f5a-acb4-69c44e4be95c',
    'vocabulary_machine_name' => 'icons',
  );
  $terms[] = array(
    'name' => 'ship',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'ff807a89-a5bd-460c-baca-ae021bc09087',
    'vocabulary_machine_name' => 'icons',
  );
  return $terms;
}
