<?php
/**
 * @file
 * news_category_taxonomy.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function news_category_taxonomy_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Public Safety and Jails',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '1659c1ec-5949-41ad-ad3c-9ece6d123305',
    'vocabulary_machine_name' => 'news_category',
    'field_icon' => array(
      'und' => array(
        0 => array(
          'tid' => 'c16c98ea-338a-4302-bb8b-eaf9a141f9ba',
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Pets and Animals',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '17bccbc1-6a85-43fe-8615-022cb94f6704',
    'vocabulary_machine_name' => 'news_category',
    'field_icon' => array(
      'und' => array(
        0 => array(
          'tid' => 'e26aa059-9d80-40df-addf-db4a5b2cfcf1',
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Health',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '1cb0f12f-61bb-416b-aa6d-1bce572e2de0',
    'vocabulary_machine_name' => 'news_category',
    'field_icon' => array(
      'und' => array(
        0 => array(
          'tid' => '3899e38c-1371-48ae-be01-64f058bf9771',
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Building and Construction',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '280dfa46-ba75-4f7c-9017-e35592e92f41',
    'vocabulary_machine_name' => 'news_category',
    'field_icon' => array(
      'und' => array(
        0 => array(
          'tid' => 'bf129741-0fd8-4634-8132-1692f4785297',
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Open Data and Transparency',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '4ad80019-8b34-44a2-9a86-6227a77c8f2a',
    'vocabulary_machine_name' => 'news_category',
    'field_icon' => array(
      'und' => array(
        0 => array(
          'tid' => 'b436e514-88c6-4bf9-9434-adea3fb8d245',
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Voting and Elections',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '5bcffe90-f1d5-4b5e-b469-6f0500b045e7',
    'vocabulary_machine_name' => 'news_category',
    'field_icon' => array(
      'und' => array(
        0 => array(
          'tid' => '0a185a84-002f-4897-8187-da7d6a5aa624',
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Homeland Security and Emergency Management',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '6aebc864-db6b-4fb7-b1a4-8522ea733552',
    'vocabulary_machine_name' => 'news_category',
    'field_icon' => array(
      'und' => array(
        0 => array(
          'tid' => 'eb886256-6a38-44e4-87e5-ca702ddc016c',
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Environmental',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '73b67c39-2cfc-4f76-9961-aa4d87ac92b3',
    'vocabulary_machine_name' => 'news_category',
    'field_icon' => array(
      'und' => array(
        0 => array(
          'tid' => 'de0610ae-657f-4fd0-a47e-de6831ff2660',
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Community',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '77fec59c-a433-4cc6-a7bb-e78f66a20154',
    'vocabulary_machine_name' => 'news_category',
    'field_icon' => array(
      'und' => array(
        0 => array(
          'tid' => '82b3a57e-00a4-417e-8a04-e504bd2db1de',
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Taxes',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '7f6afff7-b32c-4022-974c-448063b654bb',
    'vocabulary_machine_name' => 'news_category',
    'field_icon' => array(
      'und' => array(
        0 => array(
          'tid' => '8f4fb8e7-5498-454f-b270-eac9d69c54b4',
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Housing and Property',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '8a3f6162-666a-421a-9edd-36218132c8ca',
    'vocabulary_machine_name' => 'news_category',
    'field_icon' => array(
      'und' => array(
        0 => array(
          'tid' => 'db2c0a6d-116b-4038-bc11-e607770e1a5c',
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Contractor and Vendor Resources',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'a851ad8f-2e96-41a2-a033-0b4ed707b69f',
    'vocabulary_machine_name' => 'news_category',
    'field_icon' => array(
      'und' => array(
        0 => array(
          'tid' => '495d0a7a-77d5-43d5-a507-6435fece1ee5',
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Outdoor Recreation',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'ae47647a-b05f-4670-8c08-02b858dc863f',
    'vocabulary_machine_name' => 'news_category',
    'field_icon' => array(
      'und' => array(
        0 => array(
          'tid' => 'ba759b57-6daf-4c69-a80a-b7b1fb35bf3a',
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Budget and Financial',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'af159be8-ee2c-49a3-bab8-6d3ae5671011',
    'vocabulary_machine_name' => 'news_category',
    'field_icon' => array(
      'und' => array(
        0 => array(
          'tid' => 'efdb6ea2-b58b-4fc1-993b-fa8b3234c2c5',
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Courts and Legal',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'afd18d18-d1bd-41fb-a8c0-696a69aa2ab0',
    'vocabulary_machine_name' => 'news_category',
    'field_icon' => array(
      'und' => array(
        0 => array(
          'tid' => '2246d37d-444a-4d5e-b105-8e48e7063478',
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Technology',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'bec6dd71-dc23-44aa-b14a-ba123ba668d4',
    'vocabulary_machine_name' => 'news_category',
    'field_icon' => array(
      'und' => array(
        0 => array(
          'tid' => '2e820cca-c47e-4cb4-b281-44a3fd18601b',
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Ordinances and Codes',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'c485c2af-f529-4acf-9b61-7e07a43caaa3',
    'vocabulary_machine_name' => 'news_category',
    'field_icon' => array(
      'und' => array(
        0 => array(
          'tid' => 'b41d37ff-7a8a-44eb-9881-54ea3fbf79d0',
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Economic Development',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'ff777aaa-5bb7-4d72-8a71-f1655f9a9474',
    'vocabulary_machine_name' => 'news_category',
    'field_icon' => array(
      'und' => array(
        0 => array(
          'tid' => 'eaa311cc-1b00-4020-bca4-14b857d01931',
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  return $terms;
}
