<?php
/**
 * @file
 * government_body_content_type.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function government_body_content_type_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Commissioner',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '043db736-ec7e-4c0e-9009-c7270d20f5c9',
    'vocabulary_machine_name' => 'government_position_types',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Secretary',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '598d52b6-a45c-4bbe-b1b6-fe8d9f31dfa1',
    'vocabulary_machine_name' => 'government_position_types',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Director',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '5c3cd95e-e68c-4a83-956f-dbd80ff8aaeb',
    'vocabulary_machine_name' => 'government_position_types',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Vice President',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '5f41a064-3a8d-4d7e-957d-36e71b9bdb2b',
    'vocabulary_machine_name' => 'government_position_types',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Chairman',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '63ba8939-8d3c-4e76-8096-aefa60818542',
    'vocabulary_machine_name' => 'government_position_types',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'President Pro Tempore',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '67ebf055-590a-4120-8f0a-648badda5f36',
    'vocabulary_machine_name' => 'government_position_types',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Chair',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '714c81c6-dbfb-422e-8f77-de043a47c86d',
    'vocabulary_machine_name' => 'government_position_types',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Treasurer',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '7d10adc3-cbdf-489d-9fa3-5190ff4021da',
    'vocabulary_machine_name' => 'government_position_types',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Vice Chairman',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '8581742b-2f1a-4926-931e-9243319bd736',
    'vocabulary_machine_name' => 'government_position_types',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Member',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'd015b6c8-aab4-44ab-9b91-4e68d92e1345',
    'vocabulary_machine_name' => 'government_position_types',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Trustee',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'd07ae6ac-34b0-43c2-95d4-041615efb282',
    'vocabulary_machine_name' => 'government_position_types',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'President',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'f4e4ed32-67b9-4051-b243-8324bc93fea4',
    'vocabulary_machine_name' => 'government_position_types',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  return $terms;
}
